# Default values for promitor-scraper.
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: tomkerkhove/promitor-agent-scraper
  tag: 1.0.0-preview-2
  pullPolicy: Always

azureAuthentication:
  appId: ""
  appKey: ""

scrapeConfig:
  path: /prometheus/scrape
  schedule: "*/5 * * * *"
  timestamp: True

telemetry:
  appInsightsKey: ""

## Metric Declaration YAML
azureMetadata:
  tenantId: ""
  subscriptionId: ""
  resourceGroupName: promitor
metricDefaults:
  aggregation:
    interval: 00:05:00
metrics: []
# Sample metric configuration below
#   - name: demo_queue_size
#     description: "Amount of active messages of the 'myqueue' queue"
#     resourceType: ServiceBusQueue
#     namespace: promitor-messaging
#     queueName: myqueue
#     azureMetricConfiguration:
#       metricName: ActiveMessages
#       aggregation:
#         type: Total
#         interval: 00:15:00

secrets:
  # To use your own secret, set createSecret to false and define the name/keys that your secret uses
  createSecret: True
  secretName: ""
  appIdSecret: azure-app-id
  appKeySecret: azure-app-key
  appInsightsSecret: azure-appinsights-key

service:
  exposeExternally: False
  port: 80
  targetPort: 9090
  labelType: infrastructure
  selectorType: runtime
