# Default values for promitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tomkerkhove/promitor-agent-scraper
  tag: 1.0.0-preview-1
  pullPolicy: Always

azureAuthentication:
  appId: ""
  appKey: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 88
  labelType: infrastructure
  selectorType: runtime

metricsConfig:
  tenantId: ""
  subscriptionId: ""
  resourceGroupName: promitor
  defaultInterval: 00:05:00
<<<<<<< HEAD
  metrics: 
=======
  metrics: []
>>>>>>> 91c23604e71a37b54f7b5bad984ad2fb4608e247
# Sample metric configuration below
#   - name: demo_queue_size
#     description: "Amount of active messages of the 'myqueue' queue"
#     resourceType: ServiceBusQueue
#     namespace: promitor-messaging
#     queueName: myqueue
#     azureMetricConfiguration:
#       metricName: ActiveMessages
<<<<<<< HEAD
#       aggregation:
#         type: Total
#         interval: 00:15:00
=======
#       aggregation: Total
>>>>>>> 91c23604e71a37b54f7b5bad984ad2fb4608e247
