# Default values for promitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tkherkove/promitor-agent-scraper
  tag: 1.0.0-preview-1
  pullPolicy: Always

azureAuthentication:
  appId: ""
  appKey: ""

service:
  type: LoadBalancer
  port: 1337
  targetPort: 88
  labelType: infrastructure
  selectorType: runtime

metricsConfig:
  tenantId: ""
  subscriptionId: ""
  resourceGroupName: promitor
  defaultInterval: 00:05:00
  metrics:
    - name: demo_queue_size
      description: "Amount of active messages of the 'myqueue' queue"
      resourceType: ServiceBusQueue
      namespace: promitor-messaging
      queueName: myqueue
      azureMetricConfiguration:
        metricName: ActiveMessages
        aggregation: Total

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
