scrape_configs:
- job_name: promitor
  scrape_interval: 5s
  metrics_path: /scrape
  static_configs:
  - targets:
    - promitor.agents.scraper:88
- job_name: traefik
  scrape_interval: 5s
  static_configs:
  - targets:
    - traefik-reverse-proxy:8080