name: Feature request 🧭 (Legacy)
about: Suggest an idea for this project
labels: "feature-request"
assignees: tomkerkhove
issue_body: true
inputs:
- type: textarea
  attributes:
    label: Proposal
    description: "What would you like to have as a feature"
    placeholder: "A clear and concise description of what you want to happen."
- type: multi_select
  attributes:
    label: Component
    description: What Promitor agent are you having issues with?
    required: true
    choices:
    - Resource Discovery
    - Scraper
- type: input
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    required: false
    placeholder: ex. email@example.com
