name: Feature request 🧭
about: Suggest an idea for this project
labels: "feature-request"
assignees: tomkerkhove
issue_body: true
body:
- type: textarea
  attributes:
    label: Proposal
    description: "What would you like to have as a feature"
    placeholder: "A clear and concise description of what you want to happen."
- type: dropdown
  attributes:
    label: Component
    description: What Promitor agent are you having issues with?
    multiple: true
    options:
    - Resource Discovery
    - Scraper
  validations:
    required: true
- type: input
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com
  validations:
    required: false
