name: Report a bug 🐛
about: Create a report to help us improve
labels: "bug"
assignees: tomkerkhove
issue_body: true
inputs:
- type: textarea
  attributes:
    label: Report
    description: "What bug have you encountered?"
    placeholder: "A clear and concise description of what the bug is."
- type: textarea
  attributes:
    label: Expected Behavior
    description: What did you expect to happen?
    required: true
    placeholder: What did you expect to happen?
- type: textarea
  attributes:
    label: Actual Behavior
    description: Also tell us, what did you see is happen?
    required: true
    placeholder: Tell us what you see that is happening
- type: textarea
  attributes:
    label: Steps to Reproduce the Problem
    description: "How can we reproduce this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      ...
    required: true
- type: dropdown
  attributes:
    label: Component
    description: What Promitor agent are you having issues with?
    required: true
    choices:
    - Scraper
    - Resource Discovery
- type: input
  attributes:
    label: Version
    description: What version are you running?
    required: true
- type: textarea
  attributes:
    label: Configuration
    description: "Provide insights in the configuration that you are using, if you can share them"
    value: |
      Configuration:

      ```yaml
      # Add your scraping configuration here
      ```
    required: false    
- type: textarea
  attributes:
    label: Logs
    description: "Provide logs of our component, if you can share them"
    value: |
      ```yaml
      example
      ```
    required: false
- type: dropdown
  attributes:
    label: Platform
    description: Where is your cluster running?
    required: false
    choices:
    - Alibaba Cloud
    - Amazon Web Services
    - Google Cloud
    - Microsoft Azure
    - Red Hat OpenShift
    - Other
- type: input
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    required: false
    placeholder: ex. email@example.com
