blank_issues_enabled: true
contact_links:
  - name: Ask a question 💬
    url: https://github.com/tomkerkhove/promitor/discussions/new
    about: Ask a question or request support for using Promitor.
  - name: Sponsor 💘
    url: https://github.com/sponsors/tomkerkhove
    about: Sponsor Tom to keep on maintaining Promitor.
