FROM mcr.microsoft.com/dotnet/sdk:6.0.202 AS build
WORKDIR /src
ARG VERSION="UNSET-VERSION"
COPY Promitor.Core/* Promitor.Core/
COPY Promitor.Agents.Core/* Promitor.Agents.Core/
COPY Promitor.Core.Scraping/* Promitor.Core.Scraping/
COPY Promitor.Core.Contracts/* Promitor.Core.Contracts/
COPY Promitor.Core.Telemetry/* Promitor.Core.Telemetry/
COPY Promitor.Integrations.Azure/* Promitor.Integrations.Azure/
COPY Promitor.Integrations.AzureMonitor/* Promitor.Integrations.AzureMonitor/
COPY Promitor.Integrations.AzureStorage/* Promitor.Integrations.AzureStorage/
COPY Promitor.Integrations.Sinks.Statsd/* Promitor.Integrations.Sinks.Statsd/
COPY Promitor.Integrations.Sinks.Atlassian.Statuspage/* Promitor.Integrations.Sinks.Atlassian.Statuspage/
COPY Promitor.Integrations.Sinks.Prometheus/* Promitor.Integrations.Sinks.Prometheus/
COPY Promitor.Agents.Scraper/* Promitor.Agents.Scraper/
RUN dotnet publish Promitor.Agents.Scraper/Promitor.Agents.Scraper.csproj --configuration release --output app /p:Version=%VERSION%

FROM mcr.microsoft.com/dotnet/aspnet:6.0.4 as runtime
WORKDIR /app
ENV PROMITOR_CONFIG_FOLDER="c:/config/"

COPY --from=build /src/app .

ENTRYPOINT ["dotnet", "Promitor.Agents.Scraper.dll"]
