apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "promitor-agent-resource-discovery.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-resource-discovery.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "promitor-agent-resource-discovery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "promitor-agent-resource-discovery.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.secrets.createSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "promitor-agent-resource-discovery.serviceaccountname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          - name: PROMITOR_AUTH_APPID
            value: {{ .Values.azureAuthentication.appId }}
          - name: PROMITOR_AUTH_APPKEY
            valueFrom:
              secretKeyRef:
                  name: {{ template "promitor-agent-resource-discovery.secretname" . }}
                  key: {{ .Values.secrets.appKeySecret }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: config-volume-{{ template "promitor-agent-resource-discovery.name" . }}
            mountPath: /config/
  {{- if .Values.health.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /api/v1/health?includeDependencies={{ .Values.health.liveness.verifyDependencies }}
              port: http
            initialDelaySeconds: {{ .Values.health.liveness.delay }}
            periodSeconds: {{ .Values.health.liveness.interval }}
  {{- end }}
  {{- if .Values.health.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /api/v1/health?includeDependencies={{ .Values.health.readiness.verifyDependencies }}
              port: http
            initialDelaySeconds: {{ .Values.health.readiness.delay }}
            periodSeconds: {{ .Values.health.readiness.interval }}
  {{- end }}
      volumes:
        - name: config-volume-{{ template "promitor-agent-resource-discovery.name" . }}
          configMap:
            name: config-map-{{ template "promitor-agent-resource-discovery.name" . }}
