name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - deploy/automation/docker-hub/ci/*
    - .azure-devops/docker-hub-bot-for-prs*
jobs:
- job: Tooling
  displayName: Verify Tooling
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - powershell: |
      $prNumber = '$(System.PullRequest.PullRequestNumber)'
      $buildNumber = '$(Build.BuildNumber)'
      Write-Host "Initial build number: '$buildNumber'"
      Write-Host "PR Number '$prNumber'"
      $buildNumber = 'PR$(System.PullRequest.PullRequestNumber)'
      Write-Host "##vso[build.updatebuildnumber]$buildNumber"
      Write-Host "Build number is '$buildNumber'"
    displayName: 'Change Build Number to PR format'
    condition: eq(variables['Build.Reason'], 'PullRequest')

  - task: AzureResourceGroupDeployment@2
    displayName: 'Validate Docker Hub Bot ARM Template'
    inputs:
      azureSubscription: 'Visual Studio Enterprise (0f9d7fea-99e8-4768-8672-06a28514f77e)'
      resourceGroupName: 'promitor'
      location: 'West Europe'
      csmFile: 'deploy/automation/docker-hub/ci/azuredeploy.json'
      csmParametersFile: 'deploy/automation/docker-hub/ci/azuredeploy.parameters.json'
      deploymentMode: Validation