name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
- repo: self
trigger:
- master
pr:
  branches:
    include:
    - master
  paths:
    include:
    - charts/*
    - .azure-devops/scraper-ci.yml
stages:
- stage: Helm
  jobs:
   - job: LintHelmChart
     displayName: Lint promitor-agent-scraper chart
     condition: succeeded()
     pool:
       vmImage: ubuntu-16.04
     steps:
     - task: HelmInstaller@0
       inputs:
        helmVersion: '2.9.1'
     - powershell: |
        mkdir output/
        helm lint charts/promitor-agent-scraper/