FROM mcr.microsoft.com/dotnet/sdk:6.0.202-alpine3.14 AS build
WORKDIR /src
ARG VERSION="UNSET-VERSION"
COPY Promitor.Agents.ResourceDiscovery/* Promitor.Agents.ResourceDiscovery/
COPY Promitor.Core.Contracts/* Promitor.Core.Contracts/
COPY Promitor.Agents.Core/* Promitor.Agents.Core/
COPY Promitor.Core/* Promitor.Core/
COPY Promitor.Core.Scraping/* Promitor.Core.Scraping/
COPY Promitor.Integrations.Azure/* Promitor.Integrations.Azure/
COPY Promitor.Integrations.AzureMonitor/* Promitor.Integrations.AzureMonitor/
COPY Promitor.Integrations.AzureStorage/* Promitor.Integrations.AzureStorage/
COPY Promitor.Integrations.Sinks.Prometheus/* Promitor.Integrations.Sinks.Prometheus/
RUN dotnet publish Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj --configuration release --output /app /p:Version=$VERSION

FROM mcr.microsoft.com/dotnet/aspnet:6.0.4-alpine3.14 AS runtime
WORKDIR /app
ENV PROMITOR_CONFIG_FOLDER="/config/"
COPY --from=build /app .

ENTRYPOINT ["dotnet", "Promitor.Agents.ResourceDiscovery.dll"]