FROM mcr.microsoft.com/dotnet/core/sdk:3.1.408 AS build
WORKDIR /src
ARG VERSION="UNSET-VERSION"
COPY Promitor.Agents.ResourceDiscovery/* Promitor.Agents.ResourceDiscovery/
COPY Promitor.Core.Contracts/* Promitor.Core.Contracts/
COPY Promitor.Agents.Core/* Promitor.Agents.Core/
COPY Promitor.Core/* Promitor.Core/
COPY Promitor.Integrations.Azure/* Promitor.Integrations.Azure/
RUN dotnet publish Promitor.Agents.ResourceDiscovery/Promitor.Agents.ResourceDiscovery.csproj --configuration release --output /app /p:Version=%VERSION%

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.14 AS runtime
WORKDIR /app
ENV PROMITOR_CONFIG_FOLDER="c:/config/"
COPY --from=build /app .

ENTRYPOINT ["dotnet", "Promitor.Agents.ResourceDiscovery.dll"]