server:
  httpPort: 88
authentication:
  mode: ServicePrincipal
  identityId: 7e2355f7-3f11-47fd-9b16-c8f8ec527a48
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
  containerLogs:
    isEnabled: true
  defaultVerbosity: information