server:
  httpPort: 88
authentication:
  mode: ServicePrincipal
  identityId: 90a927a2-fa24-414a-a961-70f574d14df9
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
  containerLogs:
    isEnabled: true
  defaultVerbosity: information