server:
  httpPort: 88
authentication:
  mode: ServicePrincipal
  identityId: bcb00b1d-7cde-4d05-b0fc-23a287697fa2
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
  containerLogs:
    isEnabled: true
  defaultVerbosity: information