server:
  httpPort: 88
authentication:
  mode: ServicePrincipal
  identityId: 67882a00-21d3-4ee7-b32a-430ea0768cd3
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
  containerLogs:
    isEnabled: true
  defaultVerbosity: information