apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "promitor.fullname" . }}
  labels:
    app: {{ template "promitor.name" . }}
    chart: {{ template "promitor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "promitor.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "promitor.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: PROMITOR_HTTP_PORT
            value: {{ .Values.promitorHttpPort }}
          - name: PROMITOR_AUTH_APPID
            valueFrom:
              secretKeyRef:
                  name: {{ template "promitor.fullname" . }}
                  key: azure-app-id
          - name: PROMITOR_AUTH_APPKEY
            valueFrom:
              secretKeyRef:
                  name: {{ template "promitor.fullname" . }}
                  key: azure-app-key
          volumeMounts:
          - name: promitor-scraper-metrics-config-volume
            mountPath: /config/
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: promitor-scraper-metrics-config-volume
          configMap:
            name: promitor-scraper-metrics-config