apiVersion: v1
kind: Secret
metadata:
  name: promitor-scraper
type: Opaque
data:
  # Provide a base64 version of the key for your Azure AD App
  # See documentation for more information - https://promitor.io/configuration/#authentication-with-azure-monitor
  PROMITOR_AUTH_APPKEY: ProvideYourOwn