{{- if and .Values.rbac.create .Values.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "promitor-agent-scraper.name" . }}
    chart: {{ template "promitor-agent-scraper.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "promitor-agent-scraper.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "promitor-agent-scraper.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "promitor-agent-scraper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
