apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "promitor-agent-scraper.name" . }}
  labels:
    app: {{ template "promitor-agent-scraper.name" . }}
    chart: {{ template "promitor-agent-scraper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "promitor-agent-scraper.name" . }}
      release: {{ .Release.Name }}
      type: {{ .Values.service.selectorType }}
  template:
    metadata:
      labels:
        app: {{ template "promitor-agent-scraper.name" . }}
        release: {{ .Release.Name }}
        type: {{ .Values.service.selectorType }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.secrets.createSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "promitor-agent-scraper.serviceaccountname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          - name: PROMITOR_AUTH_APPID
            valueFrom:
              secretKeyRef:
                  name: {{ template "promitor-agent-scraper.secretname" . }}
                  key: {{ .Values.secrets.appIdSecret }}
          - name: PROMITOR_AUTH_APPKEY
            valueFrom:
              secretKeyRef:
                  name: {{ template "promitor-agent-scraper.secretname" . }}
                  key: {{ .Values.secrets.appKeySecret }}
  {{- if .Values.metricSinks.atlassianStatuspage.apiKey }}
          - name: PROMITOR_ATLASSIAN_STATUSPAGE_APIKEY
            valueFrom:
              secretKeyRef:
                  name: {{ template "promitor-agent-scraper.secretname" . }}
                  key: {{ .Values.secrets.atlassianStatuspageApiKey }}
  {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: config-volume-{{ template "promitor-agent-scraper.name" . }}
            mountPath: /config/
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
      volumes:
        - name: config-volume-{{ template "promitor-agent-scraper.name" . }}
          configMap:
            name: config-map-{{ template "promitor-agent-scraper.name" . }}
