{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "promitor-agent-scraper.secretname" . }}
  labels:
    app: {{ template "promitor-agent-scraper.name" . }}
    chart: {{ template "promitor-agent-scraper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ .Values.secrets.appIdSecret }}: {{ .Values.azureAuthentication.appId | b64enc | quote }}
  {{ .Values.secrets.appKeySecret }}: {{ .Values.azureAuthentication.appKey | b64enc | quote }}
{{- end }}
