{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "promitor-agent-scraper.secretname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-scraper.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.appIdSecret }}: {{ .Values.azureAuthentication.appId | b64enc | quote }}
  {{ .Values.secrets.appKeySecret }}: {{ .Values.azureAuthentication.appKey | b64enc | quote }}
  {{- if .Values.metricSinks.atlassianStatuspage.apiKey }}
  {{ .Values.secrets.atlassianStatuspageApiKey }}: {{ .Values.metricSinks.atlassianStatuspage.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
