image:
  repository: tomkerkhove/promitor-agent-scraper-ci
  tag: pr1417
azureAuthentication:
  appId: ceb249a3-44ce-4c90-8863-6776336f5b7e
  appKey: ZgLy6zYNh9SEmIl0B+rv+ZuQQ2wJyQi/tTXnp2Wp9PM=
metricSinks:
  prometheusScrapingEndpoint:
    metricUnavailableValue: -1
    baseUriPath: /scrape
    enableMetricTimestamps: true # true by default
    enableServiceDiscovery: true
  atlassianStatuspage:
    pageId: y79z9b78ybgs
    apiKey: 53dbaf1c-8551-48ef-81f9-481eb3ac64cb
    systemMetricMapping:
    - id: nfkgnrwpn545
      promitorMetricName: promitor_demo_appplan_percentage_cpu
azureMetadata:
  tenantId: c8819874-9e56-4e3f-b1a8-1c0325138f27
  subscriptionId: 0f9d7fea-99e8-4768-8672-06a28514f77e
  resourceGroupName: promitor
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: promitor_demo_appplan_percentage_cpu
    description: "Average percentage of memory usage on an Azure App Plan"
    resourceType: AppPlan
    azureMetricConfiguration:
      metricName: MemoryPercentage
      aggregation:
        type: Average
    resources:
    - appPlanName: promitor-app-plan
      resourceGroupName: promitor-sources
  - name: azure_container_registry_total_pull_count_discovered
    description: "Amount of images that were pulled from the container registry"
    resourceType: ContainerRegistry
    azureMetricConfiguration:
      metricName: TotalPullCount
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: container-registry-landscape
  - name: promitor_demo_appplan_percentage_cpu_discovered
    description: "Average percentage of memory usage on an Azure App Plan"
    resourceType: AppPlan
    azureMetricConfiguration:
      metricName: MemoryPercentage
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: app-plan-landscape
  - name: promitor_demo_webapp_cpu_discovery
    description: "Amount of CPU time used for an Azure Web App"
    resourceType: WebApp
    azureMetricConfiguration:
      metricName: CpuTime
      aggregation:
        type: Total
    resourceDiscoveryGroups:
    - name: web-app-landscape
  - name: promitor_demo_function_memory_discovery
    description: "Average memory for an Azure Function App"
    resourceType: FunctionApp
    azureMetricConfiguration:
      metricName: MemoryWorkingSet
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: function-app-landscape
  - name: azure_logic_apps_failed_run
    description: "Total amount of failed runs for Azure Logic Apps"
    resourceType: LogicApp
    azureMetricConfiguration:
      metricName: RunsFailed
      aggregation:
        type: Total
    resources:
    - workflowName: promitor-automation-github-ci-scraper
  - name: azure_logic_apps_failed_run_discovery
    description: "Total amount of failed runs for Azure Logic Apps"
    resourceType: LogicApp
    azureMetricConfiguration:
      metricName: RunsFailed
      aggregation:
        type: Total
    resourceDiscoveryGroups:
    - name: logic-apps-unfiltered
  - name: azure_storage_account_capacity_discovery
    description: "The average capacity used in the storage account"
    resourceType: StorageAccount
    azureMetricConfiguration:
      metricName: UsedCapacity
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: storage-accounts
  - name: azure_sql_database_cpu_percent_discovery
    description: "The CPU percentage used by an Azure SQL Database."
    resourceType: SqlDatabase
    azureMetricConfiguration:
      metricName: cpu_percent
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: sql-databases
  - name: promitor_demo_azuresqlmanagedinstance_nodes_discovery
    description: "The amount of nodes for an Azure SQL Managed Instance."
    resourceType: SqlManagedInstance
    azureMetricConfiguration:
      metricName: virtual_core_count
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: sql-managed-instances
  - name: azure_network_interface_bytes_received_rate_discovery
    description: "Number of bytes the Network Interface sent"
    resourceType: NetworkInterface
    azureMetricConfiguration:
      metricName: BytesReceivedRate
      aggregation:
        type: Average
    resourceDiscoveryGroups:
    - name: network-interfaces
  - name: azure_event_hubs_incoming_messages_discovery
    description: "The number of incoming messages on an Azure Event Hub namespace"
    resourceType: EventHubs
    azureMetricConfiguration:
      metricName: IncomingMessages
      aggregation:
        type: Total
    resourceDiscoveryGroups:
    - name: event-hubs-landscape
  - name: promitor_demo_servicebus_messagecount_discovered
    description: "Average percentage of memory usage on an Azure App Plan"
    resourceType: ServiceBusNamespace
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Total
    resourceDiscoveryGroups:
    - name: service-bus-landscape
  - name: promitor_demo_app_insights_dependency_duration
    description: "Average dependency duration per dependency type"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/duration
      dimension:
        name: dependency/type
      aggregation:
        type: Average
    resources:
    - resourceUri: Microsoft.Insights/Components/docker-hub-metrics
      resourceGroupName: docker-hub-metrics
  - name: promitor_demo_app_insights_dependency_duration_200_OK
    description: "Average dependency duration per dependency type"
    resourceType: Generic
    azureMetricConfiguration:
      metricName: dependencies/duration
      aggregation:
        type: Average
    resources:
    - resourceUri: Microsoft.Insights/Components/docker-hub-metrics
      resourceGroupName: docker-hub-metrics
      filter: dependency/resultCode eq '200'
runtime:
  api:
    prefix: scraper/apis
service:
  loadBalancer:
    enabled: true
    azure:
      dnsPrefix: promitor-scraper
telemetry:
  defaultLogLevel: information
  applicationInsights:
    enabled: true
    key: 7b44b819-f5ad-4e2e-ae73-cd693046b8ae
resourceDiscovery:
  host: promitor-agent-resource-discovery
  port: 8889
  enabled: true
health:
  readiness:
    # enabled: false
    delay: 15
    interval: 5
  liveness:
    # enabled: false
    delay: 15
    interval: 30