server:
  httpPort: 88
authentication:
  mode: ServicePrincipal
  identityId: 65351cf0-33f8-4f26-9b6f-3380cf910b50
metricSinks:
  prometheusScrapingEndpoint:
    metricUnavailableValue: -1
    enableMetricTimestamps: true # true by default
    baseUriPath: /scrape
  statsd:
    host: graphite
    port: 8125
    metricPrefix: promitor.
  # atlassianStatuspage:
  #   pageId: 4mwc0ny6bgw1
  #   systemMetricMapping:
  #   - id: 333802sjqpr9
  #     promitorMetricName: promitor_demo_documentation_availability
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
    verbosity: warning
  containerLogs:
    isEnabled: true
    verbosity: information
  defaultVerbosity: information
azureMonitor:
  logging:
    informationLevel: Headers
    isEnabled: false
resourceDiscovery:
  host: promitor.agents.resourcediscovery
  port: 88