server:
  httpPort: 88
prometheus:
  metricUnavailableValue: NaN
  enableMetricTimestamps: true # true by default
  scrapeEndpoint:
    baseUriPath: /metrics-deprecated
metricSinks:
  prometheusScrapingEndpoint:
    metricUnavailableValue: NaN
    enableMetricTimestamps: true # true by default
    baseUriPath: /metrics
  statsd:
    host: graphite
    port: 8125
    metricPrefix: promitor.
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: true
    verbosity: warning
  containerLogs:
    isEnabled: true
    verbosity: trace
  defaultVerbosity: trace
azureMonitor:
  logging:
    informationLevel: Headers
    isEnabled: true
resourceDiscovery:
  host: promitor.agents.resourcediscovery
  port: 88