server:
  httpPort: 88
authentication:
  mode: ServicePrincipal
  identityId: bd16d14f-7161-432b-86ad-0c31dfef44ac
metricSinks:
  atlassianStatuspage:
    pageId: 4mwc0ny6bgw1
    systemMetricMapping:
    - id: 333802sjqpr9
      promitorMetricName: promitor_demo_documentation_availability
  openTelemetryCollector:
    collectorUri: http://opentelemetry-collector:4317
  prometheusScrapingEndpoint:
    metricUnavailableValue: -1
    enableMetricTimestamps: true # true by default
    baseUriPath: /metrics
  statsd:
    host: graphite
    port: 8125
    metricPrefix: promitor.
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
    verbosity: warning
  containerLogs:
    isEnabled: true
    verbosity: information
  defaultVerbosity: information
azureMonitor:
  logging:
    informationLevel: Headers
    isEnabled: false
resourceDiscovery:
  host: promitor.agents.resourcediscovery
  port: 88