server:
  httpPort: 88
metricSinks:
  prometheusScrapingEndpoint:
    metricUnavailableValue: -1
    enableMetricTimestamps: true # true by default
    baseUriPath: /scrape
  statsd:
    host: graphite
    port: 8125
    metricPrefix: promitor.
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: false
    verbosity: warning
  containerLogs:
    isEnabled: true
    verbosity: information
  defaultVerbosity: information
azureMonitor:
  logging:
    informationLevel: Headers
    isEnabled: false
resourceDiscovery:
  host: promitor.agents.resourcediscovery
  port: 88