name: CI - Container

on:
  workflow_dispatch:
  pull_request:
    paths:
    - .github/workflows/ci-container.yml
    - src/**

jobs:
  scan_scaper_linux:
    name: Scan Scraper Agent (Linux)
    uses: ./.github/workflows/templates-scan-image.yml
    with:
      image_name: local/scraper:${{ github.sha }}
      project_name: Promitor.Agents.Scraper
      github_runner: ubuntu-latest
      os: linux
  scan_scaper_windows:
    name: Scan Scraper Agent (Windows)
    uses: ./.github/workflows/templates-scan-image.yml
    with:
      image_name: local/scraper:${{ github.sha }}
      project_name: Promitor.Agents.Scraper
      github_runner: windows-latest
      os: windows
  scan_resource_discovery_linux:
    name: Scan Resource Discovery Agent (Linux)
    uses: ./.github/workflows/templates-scan-image.yml
    with:
      image_name: local/resource-discovery:${{ github.sha }}
      project_name: Promitor.Agents.ResourceDiscovery
      github_runner: ubuntu-latest
      os: linux
  scan_resource_discovery_windows:
    name: Scan Resource Discovery Agent (Windows)
    uses: ./.github/workflows/templates-scan-image.yml
    with:
      image_name: local/resource-discovery:${{ github.sha }}
      project_name: Promitor.Agents.ResourceDiscovery
      github_runner: windows-latest
      os: windows