name: Push Preview Images

on:
  workflow_dispatch:
  pull_request:
    paths:
    - .github/workflows/preview-images.yml
    - src/**

jobs:
  ship_scraper_preview:
    name: Ship Scraper Preview
    uses: ./.github/workflows/templates-build-push-image.yml
    with:
      image_name: ghcr.io/tomkerkhove/promitor-agent-scraper-preview
      project_name: Promitor.Agents.Scraper
      version: '2.9.0'
      os: linux
      github_runner: ubuntu-latest