on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      project_name:
        required: true
        type: string
      github_runner:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  scan:
    name: Scan Image
    runs-on: ${{ inputs.github_runner }}
    steps:
        # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build ./src/ --file ./src/${{ inputs.project_name }}/Dockerfile.${{ inputs.os }} --build-arg VERSION="1.2.3" -t ${{ inputs.image_name }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ inputs.image_name }}'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'